"""Runtime-neutral contracts for the Continuum-style baseline."""

from .clock import Clock, FakeClock, SystemMonotonicClock
from .config import ContinuumConfig, RetentionMode, SchedulerMode
from .events import (
    BlockEvicted,
    BlocksObserved,
    FollowupCancelled,
    FollowupWaiting,
    LifecycleEvent,
    LifecycleEventType,
    ProgramCompleted,
    ProgramStarted,
    RequestAdmitted,
    RequestArrived,
    RequestPreempted,
    ToolGapEnded,
    ToolGapStarted,
    TurnFinished,
)
from .logging import (
    FrozenJsonObject,
    InMemoryEventSink,
    NullEventSink,
    StructuredEventSink,
    StructuredLogEvent,
    StructuredLogRecord,
)
from .selection import (
    BlockEligibilitySnapshot,
    EligibilityPreparation,
    EligibilityTier,
    PressureReleaseEffect,
    RetentionEntryKey,
    SelectionPlan,
)
from .snapshots import (
    EvictedRequestQueueDelayRecord,
    PrefixAssociationSnapshot,
    RetentionEntrySnapshot,
    SchedulingCandidate,
    TTLDecision,
    TTLHistoryMode,
    TTLInput,
)
from .types import (
    BlockIdentity,
    ExternalToolDurationRecord,
    InputProvenance,
    InputSource,
    PrefixIdentity,
    ProgramIdentity,
    RequestIdentity,
    ServerInterRequestGapRecord,
)

__all__ = [
    "BlockEligibilitySnapshot",
    "BlockEvicted",
    "BlockIdentity",
    "BlocksObserved",
    "Clock",
    "ContinuumConfig",
    "EligibilityPreparation",
    "EligibilityTier",
    "EvictedRequestQueueDelayRecord",
    "ExternalToolDurationRecord",
    "FakeClock",
    "FollowupCancelled",
    "FollowupWaiting",
    "FrozenJsonObject",
    "InMemoryEventSink",
    "InputProvenance",
    "InputSource",
    "LifecycleEvent",
    "LifecycleEventType",
    "NullEventSink",
    "PrefixAssociationSnapshot",
    "PrefixIdentity",
    "PressureReleaseEffect",
    "ProgramCompleted",
    "ProgramIdentity",
    "ProgramStarted",
    "RequestAdmitted",
    "RequestArrived",
    "RequestIdentity",
    "RequestPreempted",
    "RetentionEntryKey",
    "RetentionEntrySnapshot",
    "RetentionMode",
    "SchedulerMode",
    "SchedulingCandidate",
    "SelectionPlan",
    "ServerInterRequestGapRecord",
    "StructuredEventSink",
    "StructuredLogEvent",
    "StructuredLogRecord",
    "SystemMonotonicClock",
    "TTLDecision",
    "TTLHistoryMode",
    "TTLInput",
    "ToolGapEnded",
    "ToolGapStarted",
    "TurnFinished",
]
