"""Runtime-neutral contracts for the Continuum-style baseline."""

from .clock import Clock, FakeClock, SystemMonotonicClock
from .config import ContinuumConfig, RetentionMode, SchedulerMode
from .events import (
    BlockEvicted,
    BlocksObserved,
    FollowupCancelled,
    FollowupWaiting,
    LifecycleEvent,
    LifecycleEventType,
    ProgramCompleted,
    ProgramStarted,
    RequestAdmitted,
    RequestArrived,
    RequestPreempted,
    ToolGapEnded,
    ToolGapStarted,
    TurnFinished,
)
from .types import (
    BlockIdentity,
    ExternalToolDurationRecord,
    InputProvenance,
    InputSource,
    PrefixIdentity,
    ProgramIdentity,
    RequestIdentity,
    ServerInterRequestGapRecord,
)

__all__ = [
    "BlockEvicted",
    "BlockIdentity",
    "BlocksObserved",
    "Clock",
    "ContinuumConfig",
    "ExternalToolDurationRecord",
    "FakeClock",
    "FollowupCancelled",
    "FollowupWaiting",
    "InputProvenance",
    "InputSource",
    "LifecycleEvent",
    "LifecycleEventType",
    "PrefixIdentity",
    "ProgramCompleted",
    "ProgramIdentity",
    "ProgramStarted",
    "RequestAdmitted",
    "RequestArrived",
    "RequestIdentity",
    "RequestPreempted",
    "RetentionMode",
    "SchedulerMode",
    "ServerInterRequestGapRecord",
    "SystemMonotonicClock",
    "ToolGapEnded",
    "ToolGapStarted",
    "TurnFinished",
]
